bootstrap:
  build: .
  environment:
    MYSQL_ROOT_PASSWORD: password
    SST_USER: xtrabackup
    SST_PASSWORD: xtrabackup
    BOOTSTRAP: "on"
    NODE_NAME: startup.db.test

joiner:
  build: .
  environment:
    MYSQL_ROOT_PASSWORD: password
    SST_USER: xtrabackup
    SST_PASSWORD: xtrabackup
    CLUSTER_MEMBERS: 172.17.0.19,172.17.0.6
    NODE_NAME: joiner.db.test
